### ISSUE TITLE
[BUG] 如何指定GPU训练？我有两块GPU，但是运行自动在小现存上，报错显存不足

### ISSUE THREAD

**Issue by SunJR24** [imClumsyPanda/langchain-ChatGLM#861]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
OutOfMemoryError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 1; 6.00 GiB total capacity; 5.33 GiB already
allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by SunJR24** [comment]
应该说如何限制只在一张显卡上运行啊，允许python webui启动时候，我的两张显卡都在工作，显存小3060-6G的爆显，直接导致运行报错，但是我还有张3090-24G的，单独运行应该可以正常跑。![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/103394223/55d1a78f-bc05-4427-b44a-041bd0641655)

**Comment by yang1111-gif** [comment]
在loader.py里面，有if 判断语句关于num_gpus < 2 and self.device_map is None的那句，加上or 'chatglm' in self.model_name.lower()

**Comment by SunJR24** [comment]
> 在loader.py里面，有if 判断语句关于num_gpus < 2 and self.device_map is None的那句，加上or 'chatglm' in self.model_name.lower()

谢谢大哥  好使
