### ISSUE TITLE
运行环境：GPU需要多大的？

### ISSUE THREAD

**Issue by ValarMorghulis2018** [imClumsyPanda/langchain-ChatGLM#9]
如果按照THUDM/ChatGLM-6B的说法，使用的GPU大小应该在13GB左右，但运行脚本后，占用了24GB还不够。

是因为langchain的RetrievalQA.from_chain_type 这个函数调用的原因还是 导入的HuggingFaceEmbeddings太大？

希望能提供模型运行时的环境配置信息，非常感谢！

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.19s/it]
Traceback (most recent call last):
  File "/home/node6/liujie/workspace/langchain-ChatGLM/knowledge_based_chatglm.py", line 11, in <module>
    from chatglm_llm import ChatGLM
  File "/home/node6/liujie/workspace/langchain-ChatGLM/chatglm_llm.py", line 9, in <module>
    class ChatGLM(LLM):
  File "pydantic/main.py", line 221, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 546, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 570, in pydantic.fields.ModelField._set_default_and_type
  File "pydantic/fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "pydantic/utils.py", line 693, in pydantic.utils.smart_deepcopy
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/node6/py_env/anaconda3/lib/python3.9/site-packages/torch/nn/parameter.py", line 55, in __deepcopy__
    result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 23.53 GiB total capacity; 22.80 GiB already allocated; 8.62 MiB free; 22.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by suc16** [comment]
HuggingFaceEmbeddings应只占2.2g显存，加载完chatGLM，langchain应该又干了点什么。。。

直接 from chatglm_llm import ChatGLM就能看出来了

**Comment by suc16** [comment]
@ValarMorghulis2018 这么改显存可以变正常

chatglm_llm.py
` 
  history = []
  tokenizer: object = None
  model: object = None

  def _init_(self):
        super().__init__()   
  def load_model(self):
        self.tokenizer = AutoTokenizer.from_pretrained(
            "/data/models/chatglm-6b",
            trust_remote_code=True
        )
        self.model = (
            AutoModel.from_pretrained(
            "/data/models/chatglm-6b",
            trust_remote_code=True)
        .half()
        .cuda()
        )`

knowledge_based_chatglm.py
`chatglm = ChatGLM()
chatglm.load_model()

def init_knowledge_vector_store(filepath):`

**Comment by imClumsyPanda** [comment]
> @ValarMorghulis2018 这么改显存可以变正常，14097MiB / 32510MiB
> 
> chatglm_llm.py
> 
> ```
>   history = []
>   tokenizer: object = None
>   model: object = None
> 
>   def _init_(self):
>         super().__init__()   
>   def load_model(self):
>         self.tokenizer = AutoTokenizer.from_pretrained(
>             "/data/models/chatglm-6b",
>             trust_remote_code=True
>         )
>         self.model = (
>             AutoModel.from_pretrained(
>             "/data/models/chatglm-6b",
>             trust_remote_code=True)
>         .half()
>         .cuda()
>         )
> ```
> 
> knowledge_based_chatglm.py
> 
> ```
> chatglm = ChatGLM()
> chatglm.load_model()
> 
> def init_knowledge_vector_store(filepath):
> ```
> 
> @imClumsyPanda 大佬看一下，现在的加载方式受langchain的LLM类影响似乎会多占显存

🙏 非常感谢提出的 solution，晚点我测试一下，有兴趣的话也可以直接发起 pull request

**Comment by suc16** [comment]
> > @ValarMorghulis2018 这么改显存可以变正常，14097MiB / 32510MiB
> > chatglm_llm.py
> > ```
> >   history = []
> >   tokenizer: object = None
> >   model: object = None
> > 
> >   def _init_(self):
> >         super().__init__()   
> >   def load_model(self):
> >         self.tokenizer = AutoTokenizer.from_pretrained(
> >             "/data/models/chatglm-6b",
> >             trust_remote_code=True
> >         )
> >         self.model = (
> >             AutoModel.from_pretrained(
> >             "/data/models/chatglm-6b",
> >             trust_remote_code=True)
> >         .half()
> >         .cuda()
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > knowledge_based_chatglm.py
> > ```
> > chatglm = ChatGLM()
> > chatglm.load_model()
> > 
> > def init_knowledge_vector_store(filepath):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @imClumsyPanda 大佬看一下，现在的加载方式受langchain的LLM类影响似乎会多占显存
> 
> 🙏 非常感谢提出的 solution，晚点我测试一下，有兴趣的话也可以直接发起 pull request

好的🆗

**Comment by imClumsyPanda** [comment]
@suc16 昨晚测试环境一直有问题，就没来得及测试，想确认一下，是不是把load_model还放在原来tokenizer和model定义的位置，只是把chatglm=ChatGLM()的位置提到函数外，也是一样的效果。

**Comment by suc16** [comment]
> @suc16 昨晚测试环境一直有问题，就没来得及测试，想确认一下，是不是把load_model还放在原来tokenizer和model定义的位置，只是把chatglm=ChatGLM()的位置提到函数外，也是一样的效果。

放在原来的位置应该会有问题，如果把model定义为类属性而非实例属性，就会触发2次加载双倍显存占用。可以试下直接python执行一条`from chatglm_llm import ChatGLM`，我这边测试没调用chatglm=ChatGLM()的时候就会加载26g显存。

**Comment by imClumsyPanda** [comment]
@suc16 好的我再研究一下 谢谢🙏

**Comment by robin087** [comment]
这个方法可行，但是我在尝试的时候，每次输入文本后都会重新加载一遍模型，感觉需要加一个flag，来记录是否已经加载过模型

**Comment by suc16** [comment]
@robin087 把chatglm=ChatGLM()挪到get_knowledge_based_answer函数外，应该不会重复加载模型的。

**Comment by robin087** [comment]
明白了，谢谢

**Comment by myml** [comment]
提交了一个pr
https://github.com/imClumsyPanda/langchain-ChatGLM/pull/17

**Comment by imClumsyPanda** [comment]
已在 2023/04/07 更新中解决。

**Comment by imClumsyPanda** [comment]
已在 chatglm_llm.py 中新增 torch_gc 函数，实现每次调用模型生成问答后清理显存。

**Comment by pltc325** [comment]
> 已在 chatglm_llm.py 中新增 torch_gc 函数，实现每次调用模型生成问答后清理显存。

我16g的卡，输入第一个问题可以正常拿到答案（91%显存占用），输入第二个问题直接显存OOM

**Comment by imClumsyPanda** [comment]
@pltc325 可以尝试把 [chatglm_llm.py 中第 51 行](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/9bb7c219ffc5ccb58d71a8e8cdf426caab2b123a/chatglm_llm.py#L51) 修改为 history = [], 会在第二个问题及之后减少缓存占用

**Comment by myml** [comment]
> > 已在 chatglm_llm.py 中新增 torch_gc 函数，实现每次调用模型生成问答后清理显存。
> 
> 我16g的卡，输入第一个问题可以正常拿到答案（91%显存占用），输入第二个问题直接显存OOM

16G有些小了，chatgml占用12G多点，文本向量化的模型也占用几个G，带历史的话，问不了几个问题

**Comment by imClumsyPanda** [comment]
昨晚提交了更新后的代码，有效减少2-3轮提问后可能存在内存爆掉的情况。
